/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.dankovic.zavrsnirad.view;

import hr.dankovic.zavrsnirad.controller.ObradaVozac;
import hr.dankovic.zavrsnirad.controller.ObradaVozilo;
import hr.dankovic.zavrsnirad.controller.ObradaVoznja;
import hr.dankovic.zavrsnirad.model.Vozac;
import hr.dankovic.zavrsnirad.model.Vozilo;
import hr.dankovic.zavrsnirad.model.Voznja;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Marko
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        //Poziv ove metode se ne smije obrisati
        initComponents();
        jmNaslovGrana.setText(Aplikacija.NASLOV_APP);

        //Nas kod pisemo nakon initComponents();
        setTitle(Aplikacija.operater.getIme() + " " + Aplikacija.operater.getPrezime());

//       if(Aplikacija.isAdmin()){
//           jmiOperateri.setVisible(false);
//       }
        jmiOperateri.setVisible(Aplikacija.isAdmin());

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmNaslovGrana = new javax.swing.JMenu();
        jmiVozila = new javax.swing.JMenuItem();
        jmiVozaci = new javax.swing.JMenuItem();
        jmiVoznje = new javax.swing.JMenuItem();
        jmiOperateri = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dankovic APP");
        setBackground(new java.awt.Color(51, 136, 143));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taxi.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(51, 136, 143));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 255));

        jmNaslovGrana.setText("NASLOV");

        jmiVozila.setText("Vozila");
        jmiVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVozilaActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiVozila);

        jmiVozaci.setText("Vozači");
        jmiVozaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVozaciActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiVozaci);

        jmiVoznje.setText("Vožnje");
        jmiVoznje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVoznjeActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiVoznje);

        jmiOperateri.setText("Operateri");
        jmiOperateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOperateriActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiOperateri);
        jmNaslovGrana.add(jSeparator1);

        jmiIzlaz.setText("Izlaz");
        jmiIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlazActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmiIzlaz);

        jMenuBar1.add(jmNaslovGrana);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_jmiIzlazActionPerformed

    private void jmiVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVozilaActionPerformed
        new Vozila().setVisible(true);
    }//GEN-LAST:event_jmiVozilaActionPerformed

    private void jmiVozaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVozaciActionPerformed
    new Vozaci().setVisible(true);    }//GEN-LAST:event_jmiVozaciActionPerformed

    private void jmiVoznjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVoznjeActionPerformed
        new Voznje().setVisible(true);
    }//GEN-LAST:event_jmiVoznjeActionPerformed

    private void jmiOperateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOperateriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiOperateriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmNaslovGrana;
    private javax.swing.JMenuItem jmiIzlaz;
    private javax.swing.JMenuItem jmiOperateri;
    private javax.swing.JMenuItem jmiVozaci;
    private javax.swing.JMenuItem jmiVozila;
    private javax.swing.JMenuItem jmiVoznje;
    // End of variables declaration//GEN-END:variables

}
